# Generated by Django 5.2.3 on 2025-06-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bikebrand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
